language: lisp
sudo: false

env:

  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell

  matrix:
    - LISP=abcl-bin
    - LISP=allegro
    - LISP=sbcl
    - LISP=cmu-bin
    - LISP=ccl-bin
    - LISP=clisp
    - LISP=ecl

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp


install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install fiveam
  - export MYDIR="$PWD"; (cd ~/.roswell/quicklisp/local-projects/ && ln -s "$MYDIR" cl-sandbox)
script:
  - ./roswell/cl-sandbox-test.ros
