language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=ecl

install:
  ./install.sh;

script:
  - cl -e '(or (and (ql:quickload :cl-sandbox) (asdf:test-system \'cl-sandbox)) (uiop:quit 1))'
