language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl-bin
    - LISP=allegro
    - LISP=sbcl
    - LISP=cmu-bin
    - LISP=ccl-bin
    - LISP=clisp
    - LISP=ecl

install:
  ./install.sh;

script:
  - ros install
